[package]
name = "embassy-usb-synopsys-otg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
critical-section = "1.1"
futures = { version = "0.3.17", default-features = false }

embassy-sync = { version = "0.5.0", path = "../embassy-sync" }
embassy-usb-driver = {version = "0.1.0", path = "../embassy-usb-driver" }
