[book]
title = "Embassy Preempt"
authors = ["liam","noah"]
language = "zh-CN"
description = "An async preempt RTOS for embedded systems, inspired by embassy & ucosii"
[output.html]
git-repository-url = "https://github.com/KMSorSMS/embassy_preempt"
