[package]
name = "embassy-stm32"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[dependencies]
embassy = { version = "0.1.0", path = "../embassy" }
embassy-macros = { version = "0.1.0", path = "../embassy-macros" }
embassy-extras = {version = "0.1.0", path = "../embassy-extras" }

defmt = { version = "0.2.0", optional = true }
log = { version = "0.4.11", optional = true }
cortex-m-rt = "0.6.13"
cortex-m = "0.7.1"
embedded-hal    = { version = "0.2.4" }
futures = { version = "0.3.5", default-features = false, features = ["async-await"] }
stm32-metapac = { path = "../../stm32-metapac"}

[features]
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]

# BEGIN GENERATED FEATURES
stm32f401cb = []
stm32f401cc = []
stm32f401cd = []
stm32f401ce = []
stm32f401rb = []
stm32f401rc = []
stm32f401rd = []
stm32f401re = []
stm32f401vb = []
stm32f401vc = []
stm32f401vd = []
stm32f401ve = []
stm32f405oe = []
stm32f405og = []
stm32f405rg = []
stm32f405vg = []
stm32f405zg = []
stm32f407ie = []
stm32f407ig = []
stm32f407ve = []
stm32f407vg = []
stm32f407ze = []
stm32f407zg = []
stm32f410c8 = []
stm32f410cb = []
stm32f410r8 = []
stm32f410rb = []
stm32f410t8 = []
stm32f410tb = []
stm32f411cc = []
stm32f411ce = []
stm32f411rc = []
stm32f411re = []
stm32f411vc = []
stm32f411ve = []
stm32f412ce = []
stm32f412cg = []
stm32f412re = []
stm32f412rg = []
stm32f412ve = []
stm32f412vg = []
stm32f412ze = []
stm32f412zg = []
stm32f413cg = []
stm32f413ch = []
stm32f413mg = []
stm32f413mh = []
stm32f413rg = []
stm32f413rh = []
stm32f413vg = []
stm32f413vh = []
stm32f413zg = []
stm32f413zh = []
stm32f415og = []
stm32f415rg = []
stm32f415vg = []
stm32f415zg = []
stm32f417ie = []
stm32f417ig = []
stm32f417ve = []
stm32f417vg = []
stm32f417ze = []
stm32f417zg = []
stm32f423ch = []
stm32f423mh = []
stm32f423rh = []
stm32f423vh = []
stm32f423zh = []
stm32f427ag = []
stm32f427ai = []
stm32f427ig = []
stm32f427ii = []
stm32f427vg = []
stm32f427vi = []
stm32f427zg = []
stm32f427zi = []
stm32f429ag = []
stm32f429ai = []
stm32f429be = []
stm32f429bg = []
stm32f429bi = []
stm32f429ie = []
stm32f429ig = []
stm32f429ii = []
stm32f429ne = []
stm32f429ng = []
stm32f429ni = []
stm32f429ve = []
stm32f429vg = []
stm32f429vi = []
stm32f429ze = []
stm32f429zg = []
stm32f429zi = []
stm32f437ai = []
stm32f437ig = []
stm32f437ii = []
stm32f437vg = []
stm32f437vi = []
stm32f437zg = []
stm32f437zi = []
stm32f439ai = []
stm32f439bg = []
stm32f439bi = []
stm32f439ig = []
stm32f439ii = []
stm32f439ng = []
stm32f439ni = []
stm32f439vg = []
stm32f439vi = []
stm32f439zg = []
stm32f439zi = []
stm32f446mc = []
stm32f446me = []
stm32f446rc = []
stm32f446re = []
stm32f446vc = []
stm32f446ve = []
stm32f446zc = []
stm32f446ze = []
stm32f469ae = []
stm32f469ag = []
stm32f469ai = []
stm32f469be = []
stm32f469bg = []
stm32f469bi = []
stm32f469ie = []
stm32f469ig = []
stm32f469ii = []
stm32f469ne = []
stm32f469ng = []
stm32f469ni = []
stm32f469ve = []
stm32f469vg = []
stm32f469vi = []
stm32f469ze = []
stm32f469zg = []
stm32f469zi = []
stm32f479ag = []
stm32f479ai = []
stm32f479bg = []
stm32f479bi = []
stm32f479ig = []
stm32f479ii = []
stm32f479ng = []
stm32f479ni = []
stm32f479vg = []
stm32f479vi = []
stm32f479zg = []
stm32f479zi = []
# END GENERATED FEATURES
