[package]
name = "embassy-stm32"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[dependencies]
embassy = { version = "0.1.0", path = "../embassy" }
embassy-macros = { version = "0.1.0", path = "../embassy-macros" }
embassy-extras = {version = "0.1.0", path = "../embassy-extras" }

defmt = { version = "0.2.0", optional = true }
log = { version = "0.4.11", optional = true }
cortex-m-rt = { version = "0.6.13", features = ["device"] }
cortex-m = "0.7.1"
embedded-hal    = { version = "0.2.4" }
futures = { version = "0.3.5", default-features = false, features = ["async-await"] }

[build-dependencies]
regex = "1.4.6"

[features]
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
_syscfg_f4 = []
_syscfg_l4 = []
_usart_v1 = []
_rng_v1 = []

# BEGIN GENERATED FEATURES
stm32f401cb = [ "_usart_v1",]
stm32f401cc = [ "_usart_v1",]
stm32f401cd = [ "_usart_v1",]
stm32f401ce = [ "_usart_v1",]
stm32f401rb = [ "_usart_v1",]
stm32f401rc = [ "_usart_v1",]
stm32f401rd = [ "_usart_v1",]
stm32f401re = [ "_usart_v1",]
stm32f401vb = [ "_usart_v1",]
stm32f401vc = [ "_usart_v1",]
stm32f401vd = [ "_usart_v1",]
stm32f401ve = [ "_usart_v1",]
stm32f405oe = [ "_usart_v1",]
stm32f405og = [ "_usart_v1",]
stm32f405rg = [ "_usart_v1",]
stm32f405vg = [ "_usart_v1",]
stm32f405zg = [ "_usart_v1",]
stm32f407ie = [ "_usart_v1",]
stm32f407ig = [ "_usart_v1",]
stm32f407ve = [ "_usart_v1",]
stm32f407vg = [ "_usart_v1",]
stm32f407ze = [ "_usart_v1",]
stm32f407zg = [ "_usart_v1",]
stm32f410c8 = [ "_usart_v1",]
stm32f410cb = [ "_usart_v1",]
stm32f410r8 = [ "_usart_v1",]
stm32f410rb = [ "_usart_v1",]
stm32f410t8 = [ "_usart_v1",]
stm32f410tb = [ "_usart_v1",]
stm32f411cc = [ "_usart_v1",]
stm32f411ce = [ "_usart_v1",]
stm32f411rc = [ "_usart_v1",]
stm32f411re = [ "_usart_v1",]
stm32f411vc = [ "_usart_v1",]
stm32f411ve = [ "_usart_v1",]
stm32f412ce = [ "_usart_v1",]
stm32f412cg = [ "_usart_v1",]
stm32f412re = [ "_usart_v1",]
stm32f412rg = [ "_usart_v1",]
stm32f412ve = [ "_usart_v1",]
stm32f412vg = [ "_usart_v1",]
stm32f412ze = [ "_usart_v1",]
stm32f412zg = [ "_usart_v1",]
stm32f413cg = [ "_usart_v1",]
stm32f413ch = [ "_usart_v1",]
stm32f413mg = [ "_usart_v1",]
stm32f413mh = [ "_usart_v1",]
stm32f413rg = [ "_usart_v1",]
stm32f413rh = [ "_usart_v1",]
stm32f413vg = [ "_usart_v1",]
stm32f413vh = [ "_usart_v1",]
stm32f413zg = [ "_usart_v1",]
stm32f413zh = [ "_usart_v1",]
stm32f415og = [ "_usart_v1",]
stm32f415rg = [ "_usart_v1",]
stm32f415vg = [ "_usart_v1",]
stm32f415zg = [ "_usart_v1",]
stm32f417ie = [ "_usart_v1",]
stm32f417ig = [ "_usart_v1",]
stm32f417ve = [ "_usart_v1",]
stm32f417vg = [ "_usart_v1",]
stm32f417ze = [ "_usart_v1",]
stm32f417zg = [ "_usart_v1",]
stm32f423ch = [ "_usart_v1",]
stm32f423mh = [ "_usart_v1",]
stm32f423rh = [ "_usart_v1",]
stm32f423vh = [ "_usart_v1",]
stm32f423zh = [ "_usart_v1",]
stm32f427ag = [ "_usart_v1",]
stm32f427ai = [ "_usart_v1",]
stm32f427ig = [ "_usart_v1",]
stm32f427ii = [ "_usart_v1",]
stm32f427vg = [ "_usart_v1",]
stm32f427vi = [ "_usart_v1",]
stm32f427zg = [ "_usart_v1",]
stm32f427zi = [ "_usart_v1",]
stm32f429ag = [ "_usart_v1",]
stm32f429ai = [ "_usart_v1",]
stm32f429be = [ "_usart_v1",]
stm32f429bg = [ "_usart_v1",]
stm32f429bi = [ "_usart_v1",]
stm32f429ie = [ "_usart_v1",]
stm32f429ig = [ "_usart_v1",]
stm32f429ii = [ "_usart_v1",]
stm32f429ne = [ "_usart_v1",]
stm32f429ng = [ "_usart_v1",]
stm32f429ni = [ "_usart_v1",]
stm32f429ve = [ "_usart_v1",]
stm32f429vg = [ "_usart_v1",]
stm32f429vi = [ "_usart_v1",]
stm32f429ze = [ "_usart_v1",]
stm32f429zg = [ "_usart_v1",]
stm32f429zi = [ "_usart_v1",]
stm32f437ai = [ "_usart_v1",]
stm32f437ig = [ "_usart_v1",]
stm32f437ii = [ "_usart_v1",]
stm32f437vg = [ "_usart_v1",]
stm32f437vi = [ "_usart_v1",]
stm32f437zg = [ "_usart_v1",]
stm32f437zi = [ "_usart_v1",]
stm32f439ai = [ "_usart_v1",]
stm32f439bg = [ "_usart_v1",]
stm32f439bi = [ "_usart_v1",]
stm32f439ig = [ "_usart_v1",]
stm32f439ii = [ "_usart_v1",]
stm32f439ng = [ "_usart_v1",]
stm32f439ni = [ "_usart_v1",]
stm32f439vg = [ "_usart_v1",]
stm32f439vi = [ "_usart_v1",]
stm32f439zg = [ "_usart_v1",]
stm32f439zi = [ "_usart_v1",]
stm32f446mc = [ "_usart_v1",]
stm32f446me = [ "_usart_v1",]
stm32f446rc = [ "_usart_v1",]
stm32f446re = [ "_usart_v1",]
stm32f446vc = [ "_usart_v1",]
stm32f446ve = [ "_usart_v1",]
stm32f446zc = [ "_usart_v1",]
stm32f446ze = [ "_usart_v1",]
stm32f469ae = [ "_usart_v1",]
stm32f469ag = [ "_usart_v1",]
stm32f469ai = [ "_usart_v1",]
stm32f469be = [ "_usart_v1",]
stm32f469bg = [ "_usart_v1",]
stm32f469bi = [ "_usart_v1",]
stm32f469ie = [ "_usart_v1",]
stm32f469ig = [ "_usart_v1",]
stm32f469ii = [ "_usart_v1",]
stm32f469ne = [ "_usart_v1",]
stm32f469ng = [ "_usart_v1",]
stm32f469ni = [ "_usart_v1",]
stm32f469ve = [ "_usart_v1",]
stm32f469vg = [ "_usart_v1",]
stm32f469vi = [ "_usart_v1",]
stm32f469ze = [ "_usart_v1",]
stm32f469zg = [ "_usart_v1",]
stm32f469zi = [ "_usart_v1",]
stm32f479ag = [ "_usart_v1",]
stm32f479ai = [ "_usart_v1",]
stm32f479bg = [ "_usart_v1",]
stm32f479bi = [ "_usart_v1",]
stm32f479ig = [ "_usart_v1",]
stm32f479ii = [ "_usart_v1",]
stm32f479ng = [ "_usart_v1",]
stm32f479ni = [ "_usart_v1",]
stm32f479vg = [ "_usart_v1",]
stm32f479vi = [ "_usart_v1",]
stm32f479zg = [ "_usart_v1",]
stm32f479zi = [ "_usart_v1",]
stm32l412c8 = []
stm32l412cb = []
stm32l412k8 = []
stm32l412kb = []
stm32l412r8 = []
stm32l412rb = []
stm32l412t8 = []
stm32l412tb = []
stm32l422cb = []
stm32l422kb = []
stm32l422rb = []
stm32l422tb = []
stm32l431cb = []
stm32l431cc = []
stm32l431kb = []
stm32l431kc = []
stm32l431rb = []
stm32l431rc = []
stm32l431vc = []
stm32l432kb = []
stm32l432kc = []
stm32l433cb = []
stm32l433cc = []
stm32l433rb = []
stm32l433rc = []
stm32l433vc = []
stm32l442kc = []
stm32l443cc = []
stm32l443rc = []
stm32l443vc = []
stm32l451cc = []
stm32l451ce = []
stm32l451rc = []
stm32l451re = []
stm32l451vc = []
stm32l451ve = []
stm32l452cc = []
stm32l452ce = []
stm32l452rc = []
stm32l452re = []
stm32l452vc = []
stm32l452ve = []
stm32l462ce = []
stm32l462re = []
stm32l462ve = []
stm32l471qe = []
stm32l471qg = []
stm32l471re = []
stm32l471rg = []
stm32l471ve = []
stm32l471vg = []
stm32l471ze = []
stm32l471zg = []
stm32l475rc = []
stm32l475re = []
stm32l475rg = []
stm32l475vc = []
stm32l475ve = []
stm32l475vg = []
stm32l476je = []
stm32l476jg = []
stm32l476me = []
stm32l476mg = []
stm32l476qe = []
stm32l476qg = []
stm32l476rc = []
stm32l476re = []
stm32l476rg = []
stm32l476vc = []
stm32l476ve = []
stm32l476vg = []
stm32l476ze = []
stm32l476zg = []
stm32l485jc = []
stm32l485je = []
stm32l486jg = []
stm32l486qg = []
stm32l486rg = []
stm32l486vg = []
stm32l486zg = []
stm32l496ae = []
stm32l496ag = []
stm32l496qe = []
stm32l496qg = []
stm32l496re = []
stm32l496rg = []
stm32l496ve = []
stm32l496vg = []
stm32l496wg = []
stm32l496ze = []
stm32l496zg = []
stm32l4a6ag = []
stm32l4a6qg = []
stm32l4a6rg = []
stm32l4a6vg = []
stm32l4a6zg = []
stm32l4p5ae = []
stm32l4p5ag = []
stm32l4p5ce = []
stm32l4p5cg = []
stm32l4p5qe = []
stm32l4p5qg = []
stm32l4p5re = []
stm32l4p5rg = []
stm32l4p5ve = []
stm32l4p5vg = []
stm32l4p5ze = []
stm32l4p5zg = []
stm32l4q5ag = []
stm32l4q5cg = []
stm32l4q5qg = []
stm32l4q5rg = []
stm32l4q5vg = []
stm32l4q5zg = []
stm32l4r5ag = []
stm32l4r5ai = []
stm32l4r5qg = []
stm32l4r5qi = []
stm32l4r5vg = []
stm32l4r5vi = []
stm32l4r5zg = []
stm32l4r5zi = []
stm32l4r7ai = []
stm32l4r7vi = []
stm32l4r7zi = []
stm32l4r9ag = []
stm32l4r9ai = []
stm32l4r9vg = []
stm32l4r9vi = []
stm32l4r9zg = []
stm32l4r9zi = []
stm32l4s5ai = []
stm32l4s5qi = []
stm32l4s5vi = []
stm32l4s5zi = []
stm32l4s7ai = []
stm32l4s7vi = []
stm32l4s7zi = []
stm32l4s9ai = []
stm32l4s9vi = []
stm32l4s9zi = []
# END GENERATED FEATURES
