[package]
name = "ucosii"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
critical-section = "1.1"
defmt = { version = "0.3", optional = true }
log = { version = "0.4.14", optional = true }

[features]
nightly = []
OS_EVENT_EN=[]
OS_EVENT_NAME_EN=[]
OS_SCHED_LOCK_EN=[]
OS_TASK_DEL_EN=[]