[package]
name = "ucosii"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
defmt-rtt = "0.4"
defmt = "0.3"
critical-section = "1.1"

[features]
defmt = []
log = []
nightly = []