[package]
name = "cyw43-pio"
version = "0.1.0"
edition = "2021"

[dependencies]
cyw43 = { path = "../" }
embassy-rp = { version = "0.1.0",  features = ["unstable-traits", "nightly", "unstable-pac", "time-driver"] }
pio-proc = "0.2"
pio = "0.2.1"
fixed = "1.23.1"
defmt = { version = "0.3", optional = true }