[package]
name = "embassy"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[features]
std = ["futures/std", "embassy-traits/std"]
defmt = ["embassy-traits/defmt", "dep:defmt"]
defmt-trace = ["embassy-traits/defmt-trace"]
defmt-debug = ["embassy-traits/defmt-debug"]
defmt-info = ["embassy-traits/defmt-info"]
defmt-warn = ["embassy-traits/defmt-warn"]
defmt-error = ["embassy-traits/defmt-error"]

[dependencies]
defmt = { version = "0.2.0", optional = true }
log = { version = "0.4.11", optional = true }

cortex-m = "0.7.1"
futures     = { version = "0.3.5", default-features = false }
pin-project = { version = "1.0.2", default-features = false }
embassy-macros  = { version = "0.1.0", path = "../embassy-macros"}
embassy-traits  = { version = "0.1.0", path = "../embassy-traits"}

