[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32F429ZITx with your chip as listed in `probe-run --list-chips`
#runner = "probe-run --chip STM32U585AIIx"
#runner = "/Users/bob/outboard-repos/probe-run/target/debug/probe-run-rp --chip STM32U585AIIx"
#runner = "/Users/bob/repos/probe-run/target/debug/probe-run --chip STM32U585AIIx"
runner = "probe-run --chip STM32U585AIIx"

[build]
target = "thumbv7em-none-eabi"
