[package]
name = "ucosii-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
ucosii-config.workspace = true
ucosii-macros-core.workspace = true
heck = "0.4.0"
if_chain = "1.0.2"
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[lib]
proc-macro = true
